spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abcdb
    username: postgres
    password: komariah321
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ilhammufid@students.amikom.ac.id
    password: dsbm ndce uaqc exop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

      logging:
        level:
          org.springframework.security: DEBUG
          com.yourpackage: DEBUG
